name: RDP Phantom Access

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Tailscale
      uses: tailscale/github-action@v2
      with:
        oauthClientId: ${{ secrets.TS_OAUTH_CLIENT_ID }}
        oauthClientSecret: ${{ secrets.TS_OAUTH_CLIENT_SECRET }}
        tags: tag:ci-github-actions

    - name: Enable RDP and Set Password
      run: |
        Set-ItemProperty -Path "HKLM:\System\CurrentControlSet\Control\Terminal Server" -Name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        net user runneradmin ${{ secrets.RDP_PASSWORD }}
        net localgroup administrators runneradmin /add

    - name: Keep Alive
      run: |
        Start-Sleep -Seconds 21600 # Keep alive for 6 hours (6 * 3600 seconds)
      shell: pwsh

